apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
